name: CI Debug

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  debug:
    name: Debug CI Issues
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Check environment
        run: |
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Working directory: $(pwd)"
          ls -la

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm ci --prefer-offline --no-audit
          echo "Dependencies installed successfully"

      - name: Verify package.json scripts
        run: |
          echo "Available scripts:"
          npm run 2>&1 | head -20 || echo "Could not list scripts"

      - name: Test lint only
        run: |
          echo "Testing lint..."
          timeout 300 npm run lint
          echo "✅ Lint completed"